#!/bin/bash

# Script complet d'installation N8N sur Debian 13

# Version test - Production-not ready - non Testé et pas validé


echo "🔄 Mise à jour et installation des prérequis "
echo "======================================================================="

# Maj systeme
sudo apt update && apt update -y

# Ajout de l’utilisateur sft au groupe sudoers
sudo usermod -aG sudo nom_de_l'utilisateur


# Installation des prérequis
sudo apt install ca-certificates curl gnupg -y

# Ajout de la clé officielle Docker
sudo install -m 0755 -d /etc/apt/keyrings

# Téléchargement et enregistrement la clé GPG officielle Docker
sudo curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Ajout du dépôt officiel Docker
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo $VERSION_CODENAME) stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Mise à jour de la liste des paquets
sudo apt update



echo "📦 Installation de Docker Engine + Compose "

# Installation de Docker Engine + Compose
sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

# Autoriser l’utilisateur à utiliser Docker sans sudo (ajout au groupe docker)
sudo usermod -aG docker nom_de_l'utilisateur

# Création du dossier du service
sudo mkdir -p /srv/n8n

# Don des droits d’accès du dossier à l’utilisateur nom_de_l'utilisateur
sudo chown -R nom_de_l'utilisateur:nom_de_l'utilisateur /srv/n8n

# Création du dossier de données persistantes
sudo mkdir /srv/n8n/n8n_data

# Génération d’une clé aléatoire & création du fichier de configuration des variables d’environnement 
sudo openssl rand -hex 32
















