#!/bin/bash

# Script complet d'installation N8N sur Debian 13

# Version test - Production-not ready - non Testé et pas validé


if [ "$EUID" -ne 0 ]; then
  echo "Veuillez lancer le script en root."
  exit
fi


echo "🔄 Mise à jour et installation des prérequis "
echo "======================================================================="

# Maj systeme
apt update && apt upgrade -y

# Ajout de l’utilisateur sft au groupe sudoers
usermod -aG sudo nom_de_l'utilisateur


# Installation des prérequis
apt install ca-certificates curl gnupg -y

# Ajout de la clé officielle Docker
install -m 0755 -d /etc/apt/keyrings

# Téléchargement et enregistrement la clé GPG officielle Docker
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Ajout du dépôt officiel Docker
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo $VERSION_CODENAME) stable" | \
tee /etc/apt/sources.list.d/docker.list > /dev/null

# Mise à jour de la liste des paquets
apt update



echo "📦 Installation de Docker Engine + Compose "

# Installation de Docker Engine + Compose
apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

# Autoriser l’utilisateur à utiliser Docker sans sudo (ajout au groupe docker)
usermod -aG docker nom_de_l'utilisateur

# Création du dossier du service
mkdir -p /srv/n8n

# Don des droits d’accès du dossier à l’utilisateur nom_de_l'utilisateur
chown -R nom_de_l'utilisateur:nom_de_l'utilisateur /srv/n8n

# Création du dossier de données persistantes
mkdir -p /srv/n8n/n8n_data

# Sauvegarde du .env existant
cp /srv/n8n/.env /srv/n8n/.env.backup

# Génération de la clé
KEY=$(openssl rand -hex 32)

# Création du nouveau .env
cat <<EOF > /srv/n8n/.env
N8N_ENCRYPTION_KEY=$KEY
N8N_SECURE_COOKIE=false

N8N_HOST=localhost
N8N_PORT=5678
N8N_PROTOCOL=http
WEBHOOK_URL=http://localhost:8080/
EOF

# Création du docker-compose.yml
cat <<EOF > /srv/n8n/docker-compose.yml
version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./n8n_data:/home/node/.n8n
EOF

# Attribution des permissions sur le dossier /srv/n8n/n8n_data
chown -R 1000:1000 /srv/n8n/n8n_data

# Lancement de N8N
cd /srv/n8n
docker compose up -d

echo "======================================================================="
echo "Installation terminée"
echo "N8N accessible sur : http://$IP:5678"
echo "======================================================================="











